FROM wangso/python3-opencv-ffmpeg:V1
MAINTAINER Songjie Wang "wangso@missouri.edu"
RUN git clone https://github.com/wangso/ImageProcessingWebServices.git
WORKDIR /ImageProcessingWebServices/Client
ENTRYPOINT ["python3", "client.py"]
